version: "3"


networks:
  ad-login:
    driver: bridge
services:
  ad-login-prod:
    container_name: ad-login-prod
    image: ad-login-prod
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    env_file:
      - prod.env